image: Ubuntu1804 # образ для сборки

stack: node 14 # окружение

branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

environment:
  access_token:
    secure: SUkMN/mFKnrgQILQu8u9EdOxRoOeaXVDaCJ1+rR7mnUj4RuVa/po5uZvt9V+8m61

install:
  - yarn install # команда установки зависимостей

build: off # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build # команда сборки



deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name rbabarov
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=build --branch=gh-pages --force --verbose
